routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OperatorController;
use Illuminate\Http\Request;
use App\Http\Controllers\BlogController;

//Namespace Auth
use App\Http\Controllers\Auth\LoginController;

//Namespace Admin
use App\Http\Controllers\Admin\AdminController;

//Namespace User
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\User\ProfileController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*SSO*/
Route::get('backend/login','SSOBrokerController@authenticateToSSO');
Route::get('authenticateToSSO','SSOBrokerController@authenticateToSSO');
Route::get('authData/{authData}','SSOBrokerController@authenticateToSSO');
Route::get('logout/{sessionId}','SSOBrokerController@logout');
Route::get('changeRole/{role}', 'SSOBrokerController@changeRole')->name('changeRole');

Route::group(['middleware' => ['SSOBrokerMiddleware']], function () {
    Route::get('test', function(){
       return 'test';
    });
 });
 
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home',[FileUploadController::class, 'index']);
Route::post('upload',[FileUploadController::class, 'upload'])->name('file.upload');

/*Sidebar*/
Route::get('/dashboard',[OperatorController::class, 'dashboard']);
Route::resource('/operator',OperatorController::class);
Route::get('/fileopd',[OperatorController::class, 'fileopd']);
Route::get('/filesaya',[OperatorController::class, 'filesaya']);
Route::get('/manajemenaplikasi',[OperatorController::class, 'manajemenaplikasi']);
Route::get('/temukandokumen',[OperatorController::class, 'temukandokumen']);


Route::group(['namespace' => 'User','middleware' => 'auth' ,'prefix' => 'user'],function(){
	Route::get('/',[UserController::class,'index'])->name('user');
	Route::get('/profile',[ProfileController::class,'index'])->name('profile');
	Route::patch('/profile/update/{user}',[ProfileController::class,'update'])->name('profile.update');
});

Route::group(['namespace' => 'Auth','middleware' => 'guest'],function(){
	Route::view('/login','auth.login')->name('login');
	Route::post('/login',[LoginController::class,'authenticate'])->name('login.post');
});

// Other
Route::view('/register','auth.register')->name('register');
Route::view('/forgot-password','auth.forgot-password')->name('forgot-password');
Route::post('/logout',function(){
	return redirect()->to('/login')->with(Auth::logout());
})->name('logout');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Models\Unit;
use Aws\Textract\TextractClient;
use App\Services\OperatorService;
use App\Models\User;
use Storage;
use Illuminate\Support\Facades\Hash;

class OperatorController extends Controller
{
    protected $OperatorService;
    function __construct(
        OperatorService $OperatorService
    ) {
        $this->OperatorService = $OperatorService;
        
    }

    public function index()
    {
        $users = $this->OperatorService->getData();
        $units = Unit::all();
        //dd($units);

        return view('operator.index', [
            'data_users' => $users,
            'data_units' => $units
        ]);
    }

    public function create()
    {
        return view('operator.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'nama'     => 'required',
            'email'   => 'required',
            'id_unit' => 'required',
            'password' => 'required',
            'role' => 'required',
            'status'     => 'required'
        ]);

        $user = User::create([
            'nama'     => $request->nama,
            'email'   => $request->email,
            'id_unit'   => $request->id_unit,
            'password' => md5($request->password),
            'role' => $request->role,
            'status'     => $request->status
        ]);

        return redirect()->route('operator.index')->with('Sukses', 'Data Berhasil Disimpan');
    }

    public function show(User $user)
    {
        return view('operator.show', compact('user'));
    }

    public function edit(User $user)
    {
        return view('operator.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'nama'     => 'required',
            'email'   => 'required',
            'id_unit' => 'required',
            'role' => 'required',
            'status'     => 'required'
        ]);

        //get data User by ID
        $user = User::findOrFail($user->id);
        $user->update([
            'nama'     => $request->nama,
            'email'   => $request->email,
            'id_unit' => $$request->id_unit,
            'role' => $request->role,
            'status'     => $request->status
        ]);
        return redirect()->route('operator.index')->with('Sukses', 'Data Berhasil Diupdate');
            
    }
    
    public function destroy(User $user)
    {
        $user->delete($user);
        return redirect()->route('operator.index')->with('Sukses', 'Data Berhasil Dihapus');
    }

    public function textract()
    {
        $client = new TextractClient([
            'region' => 'us-west-2',
            'version' => '2018-06-27',
            'credentials' => [
                'key'    => 'AKIA5UACA4RFIG2XXFVD',
                'secret' => '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'
            ]
        ]);

        // The file in this project.
        $filename = "a.pdf";
        $file = fopen($filename, "rb");
        $contents = fread($file, filesize($filename));
        fclose($file);
        $options = [
            'Document' => [
                'Bytes' => $contents
            ],
            'FeatureTypes' => ['TABLES'], ['FORMS'] // REQUIRED
        ];
        $result = $client->analyzeDocument($options);
        // If debugging:
        // echo print_r($result, true);
        $blocks = $result['Blocks'];
        // Loop through all the blocks:
        foreach ($blocks as $key => $value) {
            if (isset($value['BlockType']) && $value['BlockType'] && $value['BlockType']) {
                $blockType = $value['BlockType'];
                if (isset($value['Text']) && $value['Text'] && $value['Text']) {
                    $text = $value['Text'];
                    if ($blockType == 'WORD') {
                        echo "Word: " . print_r($text, true) . "\n";
                    } else if ($blockType == 'LINE') {
                        echo "Line: " . print_r($text, true) . "\n";
                    } else if ($blockType == 'TABLE') {
                        echo "Table: " . print_r($text, true) . "\n";
                    }
                }
            }
        }
    }

    public function dashboard()
    {
        return view('template.dashboard');
    }

    public function operator()
    {
        return view('operator.index');
    }

    public function fileopd()
    {
        return view('template.fileopd');
    }

    public function filesaya()
    {
        return view('template.filesaya');
    }

    public function manajemenaplikasi()
    {
        return view('template.manajemenaplikasi');
    }

    public function temukandokumen()
    {
        return view('template.temukandokumen');
    }
}

resources/views/operator/create.blade.php
<div class="modal fade" id="m_operator" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Operator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Input gagal.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('operator.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('POST')

                <div class="column">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label class="font-weight-bold">Nama</label>
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" placeholder="Masukkan Nama Anda">

                            <!-- error message untuk title -->
                            @error('nama')
                            <div class="alert alert-danger mt-2">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Alamat Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" placeholder="Masukkan Email Anda">

                                <!-- error message untuk title -->
                                @error('email')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" placeholder="Masukkan Password Anda">

                                <!-- error message untuk title -->
                                @error('password')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">OPD</label>
                                <select class="form-control" name="id_unit" id="id_unit">
                                    @foreach ($data_units as $unit)
                                    <option value="{{$unit->id}}">{{$unit->nama}}</option>
                                    @endforeach
                                    <!-- <option value="Dinas Komunikasi, Informatika dan Statistik" {{ old('created_unit_id')=='Dinas Komunikasi, Informatika dan Statistik' ? 'selected': '' }}>Dinas Komunikasi, Informatika dan Statistik</option>
                                    <option>Dinas Kesehatan</option>
                                    <option>Dinas Pendidikan, Kepemudaan dan Olahraga</option>
                                    <option>Dinas Perhubungan</option>
                                    <option>Dinas Kehutanan dan Lingkungan Hidup</option>
                                    <option>Dinas Perindustrian dan Perdagangan</option> -->
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Role</label>
                                <select class="form-control" name="role" id="role">
                                    <option value="Admin" {{ old('role')=='Admin' ? 'selected': '' }}>Admin</option>
                                    <option value="User" {{ old('role')=='User' ? 'selected': '' }}>User</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Status</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="Aktif" {{ old('status')=='Aktif' ? 'selected': '' }}>Aktif</option>
                                    <option value="Nonaktif" {{ old('status')=='Nonaktif' ? 'selected': '' }}>Tidak Aktif</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-md btn-warning">Reset</button>
                        <button type="submit" class="btn btn-md btn-primary">Tambah</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/operator/delete.blade.php
<div class="modal fade" id="m_operator_hapus" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <form action="{{ route('operator.destroy',$user->id) }}" method="POST">
                @csrf
                @method('DELETE')
                
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Hapus Operator</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="$user->id" id="$user->id">
        <h5>Apakah Anda Yakin Ingin Menghapus ?</h5>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Ya</button>
      </div>
    </div>
  </div>
</div>

resources/views/operator/edit.blade.php
<div class="modal fade" id="m_operator_edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Operator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Input gagal.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            
            <form action="{{ route('operator.update',$user->id) }}" method="POST" id="editForm">
                @csrf
                @method('PUT')

                <div class="column">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label class="font-weight-bold">Nama</label>
                            <input type="text" name="nama" class="form-control" id="nama">
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Alamat Email</label>
                                <input type="email" name="email" class="form-control" id="email">
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">OPD</label>
                                <select class="form-control" name="id_unit" id="id_unit">
                                    @foreach ($data_units as $unit)
                                    <option value="{{$unit->id}}">{{$unit->nama}}</option>
                                    @endforeach
                                    <!-- <option value="Dinas Komunikasi, Informatika dan Statistik" {{ old('created_unit_id')=='Dinas Komunikasi, Informatika dan Statistik' ? 'selected': '' }}>Dinas Komunikasi, Informatika dan Statistik</option>
                                    <option>Dinas Kesehatan</option>
                                    <option>Dinas Pendidikan, Kepemudaan dan Olahraga</option>
                                    <option>Dinas Perhubungan</option>
                                    <option>Dinas Kehutanan dan Lingkungan Hidup</option>
                                    <option>Dinas Perindustrian dan Perdagangan</option> -->
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Role</label>
                                <select class="form-control" name="role" id="role">
                                    <option value="Admin" {{ old('role')=='Admin' ? 'selected': '' }}>Admin</option>
                                    <option value="User" {{ old('role')=='User' ? 'selected': '' }}>User</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Status</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="Aktif" {{ old('status')=='Aktif' ? 'selected': '' }}>Aktif</option>
                                    <option value="Nonaktif" {{ old('status')=='Nonaktif' ? 'selected': '' }}>Tidak Aktif</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-md btn-warning">Reset</button>
                        <button type="submit" id="saveModalButton" class="btn btn-md btn-primary">Tambah</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/operator/show.blade.php
<div class="modal fade" id="m_operator_show" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Show Operator</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Input gagal.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

                <div class="column">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <label class="font-weight-bold">Nama</label>
                            <input type="text" name="nama" class="form-control" id="nama" readonly>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Alamat Email</label>
                                <input type="email" name="email" class="form-control" id="email" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">OPD</label>
                                <input type="text" name="id_unit" class="form-control" id="id_unit" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Role</label>
                                <input type="text" name="role" class="form-control" id="role" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <label class="font-weight-bold">Status</label>
                                <input type="text" name="status" class="form-control" id="status" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>